CREATE TABLE personas3(
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
age INT,
email VARCHAR(50),
created DATETIME DEFAULT CURRENT_TIMESTAMP(),
UNIQUE (id),
PRIMARY KEY (id),
CHECK(age >= 18)
);